export const ON_CREATE_TICKET_MODALTOGGLE = 'ON_CREATE_TICKET_MODALTOGGLE'
export const ADD_CREATE_TICKET_LIST = 'ADD_CREATE_TICKET_LIST'
export const ASSIGN_TICKET_TOGGLE = 'ASSIGN_TICKET_TOGGLE'
export const ASSIGN_LIST = 'ASSIGN_LIST'
